### ISSUE TITLE
No cellular data

### ISSUE THREAD

**Issue by ThisIsntAnUsername** [LineageOS/android_device_motorola_lake#3]
Hey ! I updated to lineageos 17.1 on my moto g7+, but cellular data doesn't work anymore... I know it's not a dns problem (connecting to an ip doesn't work either), I already tried resetting all network settings, and wi-fi, bluetooth, phone and sms do work. It shows me the cellular data icon fine (no cross, I see connexion strength), but I just get "network unreachable" whenever I try to use it... Any idea how to solve this ?

**Comment by davewood** [comment]
sorry no idea what went wrong but for the record, it does work on my Moto G7+. I have the dual sim version.

if you have the dual sim version aswell, have you tried using the other sim slot?

**Comment by ThisIsntAnUsername** [comment]
Oh, I actually forgot to close this after I solved the issue. I asked my operator for the config settings and setting them manually solved the problem.
